package contestant;

import java.io.Serializable;

public interface Contender extends Serializable, Cloneable {
	
	/**
	 * Note that this method is called by the {@link Judge} object to set the value of this
	 * {@link Contender} in the implementations provided in this package. If the value has been 
	 * previously set, those classes will overwrite the value.
	 * 
	 * @return the ID generated by the {@link Judge} object.
	 */
	int getID();
	
	void setID(int ID);
}
